from . import walloniades_walloniade
from . import walloniades_equipe
from . import walloniades_res_partner
from . import walloniades_type_epreuve
from . import walloniades_epreuve
from . import walloniades_resultat_point
from . import walloniades_epreuve_instance
from . import walloniades_equipe_instance
from . import walloniades_resultat_temps_penalite
from . import walloniades_resultat_temps_positif_negatif
from . import walloniades_resultat_temps_niveau
from . import walloniades_classement_line
from . import walloniades_classement_general_line